### ISSUE TITLE
Why remove all components with a correlation > 0.1 to the EOG channels?

### ISSUE THREAD

**Issue by balandongiv** [AaltoImagingLanguage/conpy#7]
May I know the logic of removing score greater than 0.1? My initial believe that stronger correlation to eog should have higher value, hence need to be retained.

 In line https://github.com/AaltoImagingLanguage/conpy/blob/2aa4f9b5ac856bddee9899ab6ccbecce2d29630d/scripts/03_ica.py#L71

**Comment by balandongiv** [comment]
Ops, you are using the default z-score instead of correlation

**Comment by wmvanvliet** [comment]
The comment is not super clear, granted.
